-- Autogenerated from MM0

namespace mm0

constant term : Type

constant term.proof : term → Prop
prefix `⊦ `:26 := term.proof
constant term.forget {p : Prop} : (term → p) → p
constant wff : Type

constant wff.proof : wff → Prop
prefix `⊦ `:26 := wff.proof
constant wff.forget {p : Prop} : (wff → p) → p

/-- Define "term" and "wff" -/
constant tze : term

constant tpl : term → term → term

constant weq : term → term → wff

constant wim : wff → wff → wff


/-- State the axioms -/
axiom a1 {t r s : term} : ⊦ wim (weq t r) (wim (weq t s) (weq r s))

axiom a2 {t : term} : ⊦ weq (tpl t tze) t

axiom mp {P Q : wff} : ⊦ P → ⊦ wim P Q → ⊦ Q


/-- Prove a theorem (Contributed by ?who?, 11-Jan-2026.) -/
theorem th1 {t : term} :
  ⊦ weq t t :=
@mp (weq (tpl t tze) t) (weq t t)
  (@a2 t)
  (@mp (weq (tpl t tze) t) (wim (weq (tpl t tze) t) (weq t t))
    (@a2 t)
    (@a1 (tpl t tze) t t))

end mm0

